# aws:
#   access_key_id: 123
#   secret_access_key: 345

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
development:
  secret_key_base:
  action_mailer:
    username:
    password:
    email_from_address:
  aws:
    s3_bucket:
    region:
    access_key_id:
    secret_access_key:
  intercom:
    app_id:
    app_secret:

test:
  secret_key_base:
