# Generate with `bin/rails encryption:init`
active_record_encryption:
  primary_key: # Required
  deterministic_key: # Required
  key_derivation_salt: # Required

development:
  secret_key_base: # Required (generate with `bin/rails secret`)
  action_mailer:
    username:
    password:
    email_from_address:  # Required
  sendgrid:
    api_key:
  cloudflare:
    account_id:
    access_key_id:
    secret_access_key:
    bucket:
test:
  secret_key_base: # Required
  action_mailer:
    username:
    password:
    email_from_address: # Required
  sendgrid:
    api_key:
  cloudflare:
    account_id:
    access_key_id:
    secret_access_key:
    bucket:

production:
  secret_key_base:
  action_mailer:
    username:
    password:
    email_from_address:
  sendgrid:
    api_key:
  cloudflare:
    account_id:
    access_key_id:
    secret_access_key:
    bucket:
